module go_glog_example

go 1.21

// Declare the dependency on glog.
// Since glog does not have version tags, we use a pseudo-version
// generated by Go's tooling that corresponds to a specific commit.

require (
	github.com/go-openapi/strfmt v0.23.0
	github.com/golang/glog v1.2.5
)

require (
	github.com/asaskevich/govalidator v0.0.0-20230301143203-a9d515a09cc2 // indirect
	github.com/go-openapi/errors v0.22.0 // indirect
	github.com/google/uuid v1.6.0 // indirect
	github.com/mitchellh/mapstructure v1.5.0 // indirect
	github.com/oklog/ulid v1.3.1 // indirect
	go.mongodb.org/mongo-driver v1.14.0 // indirect
)
